la var cino "CNR number"
la var state_code "State code"
la var dist_code "District code"
la var court_no "Court number"
la var judge_desg "Judge designation"
la var def_male "Male defendant"
la var def_female "Female defendant"
la var judge_male "Male judge"
la var judge_female "Female judge"
la var def_muslim "Muslim defendant"
la var def_nonmuslim "Non-muslim defendant"
la var judge_muslim "Muslim judge"
la var judge_nonmuslim "Non-muslim judge"
la var date "Decision date or last hearing date"
la var purpose_name "Purpose name - partially cleaned"
la var purpose_name_raw "Purpose name - raw"
la var disp_name "Disposition name - clean"
la var disp_name_raw "Disposition name - raw"
la var date_first_list "Date of first hearing"
la var date_next_list "Date of next hearing"
la var district_name "District name"
la var state_name "State name"
la var type_name "Case type name"
la var decision_year "Decision year"
la var filing_year "Filing year"
la var decision_date "Date of decision"
la var filing_date "Date of filing"
la var first_hearing "Date of first hearing"
la var first_year "Year of first hearing"
la var delay "Delay"
la var year "Year - extracted from CINO"
la var topcoded_delay "Delay - top-coded"
la var court_name "Court name"
la var last_year "Year of last hearing"
la var last_hearing "Date of last hearing"
la var judge_desg_raw "Raw judge designation"
la var position "Clean judge designation"
la var tenure_start "Tenure start date"
la var tenure_end "Tenure end date"
la var act "Act"
la var section "Section"
la var offenses "Offenses"
la var offense1 "Abetment"
la var offense2 "Criminal conspiracy"
la var offense3 "Against the state"
la var offense4 "Army, navy, or force"
la var offense5 "Disturbed public tranquility"
la var offense6 "Offenses by public servants/Election fraud"
la var offense7 "Contempt of public servant"
la var offense8 "Falsifying evidence/disrupting judicial process"
la var offense9 "Coins and stamps"
la var offense10 "Weights and measures"
la var offense11 "Endangered public health or safety"
la var offense12 "Obscenity, nuisance, and lotteries"
la var offense13 "Religious offenses"
la var offense14 "Suicide, homicide, dowry death, abetment of suicide"
la var offense15 "Forced miscarriage and infanticide"
la var offense16 "Hurt"
la var offense17 "Confinement"
la var offense18 "Assault"
la var offense19 "Kidnapping"
la var offense20 "Trafficking and slavery"
la var offense21 "Sexual assault"
la var offense22 "Theft"
la var offense23 "Robbery/dacoity"
la var offense24 "Extortion"
la var offense25 "Property"
la var offense26 "Criminal breach of trust"
la var offense27 "Cheating"
la var offense28 "Fraudelence"
la var offense29 "Mischief"
la var offense30 "Trespassing"
la var offense31 "Forgery of documents and accounts"
la var offense32 "Counterfeiting property or other marks"
la var offense33 "Breach of contracts of service"
la var offense34 "Marriage offenses/adultery"
la var offense35 "Defamation"
la var offense36 "Intimidation"
la var offense37 "Commit offence - Section 511"
