name: py_spatial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bokeh=3.0.3
  - gdal=3.6.1
  - geos=3.11.1
  - geopandas=0.12.2
  - geotiff=1.7.1
  - git=2.39.0
  - haversine=2.7.0
  - mamba=1.1.0
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - notebook=6.5.2
  - numpy=1.23.5
  - pandas=1.5.2
  - pdbpp=0.10.3
  - pip=22.3.1
  - plotly=5.11.0
  - proj=9.1.0
  - pygeos=0.14
  - pytest=7.1.2
  - python=3.10.8
  - pysal=2.7.0
  - pyyaml=6.0
  - rasterio=1.3.4
  - rasterstats=0.17.0
  - rtree=1.0.1
  - segregation=2.3.1
  - shapely=2.0.0
  - tmux=3.3
  - topojson=1.5